[package]
description = "Dremio Rust client"
edition = "2021"
license = "MIT"
name = "dremio-rs"
version = "0.1.1"
repository = "https://github.com/vrd83/dremio-rs"

[dependencies]
anyhow = "1.0.93"
arrow = "53.3.0"
arrow-flight = { version = "53.3.0", features = ["flight-sql-experimental"] }
futures = "0.3.31"
parquet = "53.3.0"
tonic = "0.12.3"

[dev-dependencies]
testcontainers = "0.23.1"
tokio = { version = "1.41.1", features = ["full"] }
reqwest = "0.12.9"