[package]
name = "dremio-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.88"
arrow = "53.0.0"
arrow-flight = { version = "53.0.0", features = ["flight-sql-experimental"] }
futures = "0.3.30"
parquet = "53.0.0"
tonic = "0.12.2"
