[package]
description = "Dremio Rust client"
edition = "2021"
license = "MIT"
name = "dremio-rs"
version = "0.1.0"

[dependencies]
anyhow = "1.0.89"
arrow = "53.0.0"
arrow-flight = { version = "53.0.0", features = ["flight-sql-experimental"] }
futures = "0.3.30"
parquet = "53.0.0"
tonic = "0.12.3"

[dev-dependencies]
testcontainers = "0.23.1"
tokio = { version = "1.16.1", features = ["full"] }
reqwest = "0.12.7"